### PR TITLE
#170764520 integrate test coverage badge

### PR DESCRIPTION
**Pull request by niyodusengaclement**
### What does this PR do?
Add test coverage badge to the readme file
### Description of Task to be completed?
 - Integrate code climate test coverage into our project
 - Configure jest coverage reporters
 - Add test coverage badge to the readme file
### How should this be manually tested?
Visit this repo and read the readme file you will see a badge called `test coverage`
### Any background context you want to provide?
N/A
### What are the relevant pivotal tracker stories?
[#170764520](https://www.pivotaltracker.com/story/show/170764520)
### screenshot
coverage

### CODE REVIEW

**Review by Skemc — APPROVED** [review]
LGTM!

**Review by Alexander96779 — APPROVED** [review]
Way to Go

**Review by ajimae — CHANGES_REQUESTED** [review]
@niyodusengaclement you need to write a dummy test, integrate the work on Travis to yours and then display a Coverage report of the dummy test.

**Comment by niyodusengaclement** [comment]
> @niyodusengaclement you need to write a dummy test, integrate the work on Travis to yours and then display a Coverage report of the dummy test.

**Comment by niyodusengaclement** [comment]
Noted  *@ajimae, *but I will need to wait for @elvis to complete jest
configuration to avoid conflicts

**Review by ajimae — APPROVED** [review]
LGTM!

**Pull request merged**
