### PR TITLE
#170764514 Setup a react App with Webpack

### PR DESCRIPTION
**Pull request by shaazk**
#### What does this PR do?
- Setup a react App with Webpack
#### Description of Task to be completed?
- Setup configure react webpack
- setup Eslint
- setup Eslint Airbnb
- Modify Readme.md
#### How should this be manually tested?
- You have to clone the repo `git clone https://github.com/Stackup-Rwanda/fan7-bn-frontend.git`
- Then After the repo cloned `cd project-folder` and run `npm i` to install all dependencies
- Run the app by `npm run dev` for development 
#### Any background context you want to provide?
N/A
#### What are the relevant pivotal tracker stories?
[#170764514](https://www.pivotaltracker.com/story/show/170764514)
#### Screenshots (if appropriate)
Screenshot from 2020-03-11 07-56-37
Screenshot from 2020-03-11 07-56-20
Screenshot from 2020-03-11 07-41-45

#### Questions 
N/A

### CODE REVIEW

**Review by bihire — APPROVED** [review]
Good job

**Review by Elvis-rugamba — APPROVED** [review]
LGTM

**Review by ajimae — COMMENTED** [review]
Nice work @shaazk please include the `dist` folder and `package-lock.json` file to `.gitignore`
🥂

**Review by ajimae — APPROVED** [review]
LGTM

**Pull request merged**
